# -*- coding: utf-8 -*-
"""CRS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gng24p6C2B9xeVIFyaKfpuvmi5pSh4fD
"""



import streamlit as st
import pandas as pd

# Load dataset
st.set_page_config(page_title="Career Counselling System", layout="wide")
@st.cache_data
def load_data():
    return pd.read_csv("career__data.csv")

df = load_data()

st.title("🌟 AI-Based Career Counselling System")

st.write("Answer the fields to discover the best career for you!")

# ✅ Extract dropdown unique values from CSV
skills_list = sorted({skill.strip().lower()
                      for row in df["skills"]
                      for skill in row.split(",")})

interests_list = sorted({intr.strip().lower()
                         for row in df["interests"]
                         for intr in row.split(",")})

education_list = sorted({edu.strip().lower()
                         for row in df["education"]
                         for edu in row.split(",")})

personality_list = sorted({pers.strip().lower()
                           for row in df["personality"]
                           for pers in row.split(",")})

# ✅ Multi-select / dropdown controls
skills = st.multiselect("Select your Skills", skills_list)
interests = st.multiselect("Select your Interests", interests_list)
education = st.selectbox("Select your Education", ["Select..."] + education_list)
personality = st.selectbox("Select your Personality Type", ["Select..."] + personality_list)

def match_input(user_list, dataset_values):
    dataset_values = [v.strip().lower() for v in dataset_values.split(",")]
    return any(word.lower() in dataset_values for word in user_list)

if st.button("🎯 Recommend Careers"):
    results = []

    for i, row in df.iterrows():
        if (match_input(skills, row["skills"]) or
            match_input(interests, row["interests"]) or
            education in row["education"].lower() or
            personality in row["personality"].lower()):
            results.append(row)

    if not results:
        st.warning("⚠ No matching careers found! Try selecting more fields.")
    else:
        st.success("✅ Best Career Recommendations:")

        for rec in results:
            st.subheader(f"🎓 {rec['recommended_career']}")
            st.write(f"📚 **Recommended Courses:** {rec['Recommendations']}")
            st.write(f"💼 **Job Roles:** {rec['jobs']}")
            st.markdown("---")

st.markdown("✨ Powered by AI & Data Analytics")